name: ara
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  google_nav_bar: ^5.0.6
  simple_gradient_text: 1.2.4
  splashscreen:
  animated_splash_screen:
  cupertino_icons: ^1.0.2
  pinput: ^2.2.31
  country_picker: ^2.0.20
  image_picker: ^0.8.7
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  shared_preferences: ^2.0.18
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Inspiration
      fonts:
        - asset: fonts/Inspiration-Regular.ttf
    - family: Cinzel
      fonts:
       - asset: fonts/Cinzel.ttf
    - family: Hind
      fonts:
        - asset: fonts/HindMadurai-Regular.ttf
